name: Github Action for LaTeX
on: [push]
jobs:
  build-tex:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: compile tex to pdf
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          Literature-Review/Literature-Review.tex
          Research/Research-Proposal.tex
    - name: upload pdf
      uses: actions/upload-artifact@v2
      with:
        name: Documents
        path: |
          Literature-Review/Literature-Review.pdf
          Research/Research-Proposal.pdf

